FROM java:latest
COPY ClienteCalculadora.java /calculadora_cliente/
COPY thrift_java/ /calculadora_cliente/thrift_java/
COPY ClienteCalculadora.class /calculadora_cliente/
COPY gen-java/ /calculadora_cliente/gen-java/
COPY ejecuta_cliente.sh /calculadora_cliente/
WORKDIR /calculadora_cliente/